### ISSUE TITLE
Using @override_storage makes test pass but code is never called

### ISSUE THREAD

**Issue by fjsj** [danifus/django_override_storage#1]
Hi! Thanks for this great tool. It helped me to write cleaner tests.

A suggestion:
Using `@override_storage` instead of `@override_storage()` makes the test pass without never calling the internal test code. IMO, this behavior is quite dangerous. Any way to make `@override_storage` always fail or behave like `@override_storage()`?

**Comment by danifus** [comment]
Thanks for the report! I missed this as the underlying decorator / context manager code was adapted from django's `override_settings` and that always requires some sort of args. The underlying problem was that, without the parenthesis, the function to be wrapped was being passed into `__init__` as the first arg. The first arg supplied (if any) should have been the storage class / object instead.

Resolved by essentially requiring that all supplied arguments (if any) must be kwargs so that we don't accidentally pass the function to be wrapped to the init methods. You may have to update your code if you have been using positional arguments but this is much safer.

**Comment by fjsj** [comment]
Thank you very much!

>
